java:
  stage: test
  before_script:
    - echo $JAVA_HOME
    - export JAVA_HOME=/home/modir/.sdkman/candidates/maven/current

  script:
  - mvn clean test
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml